const { execSync } = require('child_process');
const fs = require('fs');

try {
  // Get current git branch
  const branch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
  console.log(`Current git branch: ${branch}`);

  // Fetch git commits from the last two months
  console.log('Fetching commits from the last 2 months...');
  const logCommand = 'git log --since="2 months ago" --pretty=format:"* **%h** - %s (%ad by %an)" --date=short';
  const logOutput = execSync(logCommand).toString().trim();

  // Create work history report structure
  const content = `# Project Work History (Last 2 Months)

This report shows developer commits and features added to the **CareerConnect / Job Hunt** repository for the last two months.

## Recent Functional Milestones (Offline/Demo Mode)
* **Frontend Mock Database Layer**: Added [mockDb.js](file:///d:/for%20opening/for%20opening/whole%20thing/36_projects/Job%2520Hunt/frontend/src/services/mockDb.js) to seed and manage local storage CRUD operations when running offline.
* **Axios Adapter Fallback**: Integrated custom Axios adapter inside [api.js](file:///d:/for%20opening/for%20opening/whole%20thing/36_projects/Job%2520Hunt/frontend/src/services/api.js) to intercept backend endpoints when using demo logins or when backend is down.
* **Mock WebSocket Presences**: Emulated WebSocket connections and typing auto-replies inside [SocketContext.jsx](file:///d:/for%20opening/for%20opening/whole%20thing/36_projects/Job%2520Hunt/frontend/src/context/SocketContext.jsx).
* **Navbar Badge Indicator**: Visual orange pulsing pill for verified Demo Mode in [Navbar.jsx](file:///d:/for%20opening/for%20opening/whole%20thing/36_projects/Job%2520Hunt/frontend/src/components/common/Navbar.jsx).

## Git Commit Logs
${logOutput ? logOutput : '*No git commits found in the last two months.*'}

---
*Generated by automated show-work utility on: ${new Date().toLocaleString()}*
`;

  // Save the report to work_history.md
  fs.writeFileSync('work_history.md', content);
  console.log('✓ Successfully generated work_history.md report.');

  // Staging, committing and pushing changes
  console.log('Staging repository modifications...');
  execSync('git add .');

  console.log('Committing changes...');
  try {
    execSync('git commit -m "feat: add offline mock backend capabilities and generate work report"');
    console.log('✓ Committed successfully.');
  } catch (commitErr) {
    console.log('Nothing to commit or commit failed (clean state). Continuing to push...');
  }

  console.log(`Pushing changes to remote origin/${branch}...`);
  execSync(`git push origin ${branch}`);
  console.log('✓ Successfully pushed changes to GitHub!');

} catch (error) {
  console.error('Error during script execution:', error.message);
  process.exit(1);
}
